name: PHPUnit
on:
  push:
    branches:
      - 4.x
      - tv4g9-issue1455-upgradeDockers
jobs:
  running-tests:
    name: "Drupal 9.4: PHP 8.1"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Automated testing
        uses: tripal/test-tripal-action@v1.0
        with:
          directory-name: 'tripal'
          modules: 'tripal tripal_biodb tripal_chado'
          php-version: '8.1'
          pgsql-version: '13'
          drupal-version: '9.4.x-dev'
          build-image: true
          dockerfile: "UseTripalDockerBackupClause"
