# Run some PHPUnit tests
name: PHPUnit-Tests

# When do we want the tests to run?
on: [push]

# Define jobs that are part of the workflow
jobs:
  # Job 1: 'build'
  run-tests:
    # Runner type
    runs-on: ubuntu-latest
    # PHP Targets
    strategy:
      fail-fast: false
      matrix:
        drupalversion: ['9.1.x-dev', '9.2.x-dev', '9.3.x-dev', '9.4.x-dev']
    # Give the builds names so we can tell them apart
    name: PHPUnit Drupal ${{ matrix.drupalversion }}

    # Steps in the sequence
    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Here we fully  build a docker using the current checked out code
      # to ensure we have not broken the install/build process.
      - name: Build the Docker
        run: |
          docker build --tag=tripaldocker:localdocker --build-arg drupalversion='${{ matrix.drupalversion }}' --build-arg chadoschema='testchado' ./
      # Just spin up docker the good ol' fashion way.
      - name: Spin up Local Docker
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal9/web/modules/contrib/tripal \
            tripaldocker:localdocker
          docker exec tripaldocker service postgresql restart
      # Runs the PHPUnit tests.
      # https://github.com/mheap/phpunit-github-actions-printer is used
      # to report PHPUnit fails in a meaningful way to github in PRs.
      # Stopped using mheap due to warning w/ phpunit8->9
      - name: Run PHPUnit Tests
        env:
          SIMPLETEST_BASE_URL: "http://localhost"
          SIMPLETEST_DB: "pgsql://drupaladmin:drupal9developmentonlylocal@localhost/sitedb"
          BROWSER_OUTPUT_DIRECTORY: "/var/www/drupal9/web/sites/default/files/simpletest"
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec -e SIMPLETEST_BASE_URL=$SIMPLETEST_BASE_URL \
            -e SIMPLETEST_DB=$SIMPLETEST_DB \
            -e BROWSER_OUTPUT_DIRECTORY=$BROWSER_OUTPUT_DIRECTORY \
            --workdir=/var/www/drupal9/web/modules/contrib/tripal \
            tripaldocker phpunit
